config/routes.rb
SingleUse::Application.routes.draw do  resources :users
  resources :questions
  resources :factoids
  root :to => 'pages#home'
  match 'survey', :to => 'pages#survey'
  match 'results', :to => 'pages#results'
  match 'about', :to => 'pages#about'
  match 'overall_results', :to => 'pages#overall_results'
  match 'results_by_age', :to => 'pages#results_by_age'
  match 'results_by_gender', :to => 'pages#results_by_gender'
  match 'results_by_setting', :to => 'pages#results_by_setting'
  match 'results_by_experience', :to => 'pages#results_by_experience'
  match 'results_by_region', :to => 'pages#results_by_region'
  match 'random', :to => 'pages#random'
end

app/models/factoid.rb
class Factoid < ActiveRecord::Base
  def self.random
    if (c = count) != 0
      find(:first, :offset =>rand(c))
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  default_scope order: "priority ASC"
  :options_array
  
  def options_array
    arr = self.options.split(' | ')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validate :survey_validator

  def survey_validator
    Question.all.each do |q|
      if(self["q#{q.id}"].nil?)
        errors.add(:base, "Must answer question #{q.id}")
      elsif (self["q#{q.id}"].empty?)
        errors.add(:base, "Must answer question #{q.id}")
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  http_basic_authenticate_with :name => "admin", :password => "singleuse", :except => :home, :except => [:home, :about, :survey, :random]
  
  def home
    @title = 'Home'
  end

  def about
    @title = 'About'
  end

  def survey
    @title = 'Survey'
    @user = User.new
  end

  def results
    @title = 'Survey Results'
  end

  def overall_results
    @title = 'Overall Results'
  end
  
  def results_by_age 
    @title = 'Results by Age'
  end
  
  def results_by_setting
    @title = 'Results by Setting'
  end
  
  def results_by_gender
    @title = 'Results by Gender'
  end
  
  def results_by_experience
    @title = 'Resutls by Experience'
  end
  
  def results_by_region
     @title = 'Results by Region'
  end
  
  def random
  
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.xml
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.xml
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(questions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    params[:locked_questions] = nil
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(root_path, notice: 'Thanks for taking the survey!') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Return a title on a per-page basis.
  def title
    base_title = "Single Use Survey"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  def body_options
    options = ""
    if(@bodytag.nil? == false)
      @bodytag.each_pair do |key,value|
        options << "#{key}='#{value}' "
      end
    end
    options
  end
  
  def singleuse_logo
    image_tag("singleuse_logo.jpg", :alt => "Single Use", :class => "round")
  end

  def emory_logo
    image_tag("emory_logo.gif", :alt => "Emory University", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def gravatar_for(email, options = { :size => 50 } )
    gravatar_image_tag(email.downcase,
                      :alt => email,
                      :class => 'gravatar',
                      :gravatar => options)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # def generate_radio_hash(object_name, method, tag_value, options={})
  #   radio_button_hash {
  #     type: 'radio'
  #     id: "#{object_name}_#{method}_#{tag_value}"
  #     name: "#{object_name}[#{method}]"
  #     value: "#{tag_value}"
  #   }
  #   type = "type='radio'"
  #   id = 
  #   name = 
  #   value = 
  #   checked = 
  #   disabled = "false"
  #   options.each_pair do |key, value|
  #   #add option to end of tag
  #   end
  #   ret_str = "<input #{type} #{id} #{name} #{value} #{checked}/>"
  # end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<%= render 'layouts/links_list' %>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to emory_logo, root_path %>
	<nav class="round">
		<%= render 'layouts/links_list' %>
	</nav>
</header>

app/views/layouts/_links_list.html.erb
<ul>
	<li><%= link_to "Home", '/' %></li>
	<li><%= link_to "Results", results_path %></li>
</ul>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/it' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
		<%= yield :head %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			</div> 
	</body>
</html>

app/views/pages/_demograph.html.erb
<!-- Demographic Specific Fixed Data -->
<% filter_question = Question.find(demograph) %>
<% filter_field = "q#{filter_question.id}" %>
<% legend = filter_question.options_array %>
<% color_options = ["FF0000","00FF00","0000FF","00FFFF","FF00FF","FFFF00"]%>
<% bar_colors = color_options[0..legend.count].join(",") %>

<!-- Process each Question -->
<% Question.all.each do |q| %>
	<!-- Param initialization -->
	<% data = [] %>
	<% labels = [] %>

	<!-- Text Display and Options Parameter Fill -->
	<% title = "Question #{q.id}" %>
	<p><b><%= title %></b> - <%= q.prompt %></p>
	<% q.options_array.each_with_index do |opt, i| %>
		<dd <%="style='font-weight: bold'" if q.answer == i+1 %>><%= i+1 %>) <%= opt %></dd>
		<% labels << "#{i+1}" %>
	<% end %>

	<!-- Setup Graph Data -->
	<% legend.each do |filter_value| %>	
		<% entry = [] %>
		<% q.options.split(' | ').each do |option| %>
			<% if filter_value == "All" %>
				<% entry << User.where("q#{q.id} = ?", option).count %>
				<% User.where("q#{q.id} = ?", option).count %>
			<% else %>
				<% entry << User.where("#{filter_field} = ? AND q#{q.id} = ?", filter_value, option).count %>
				<% User.where("#{filter_field} = ? AND q#{q.id} = ?", filter_value, option).count %>
			<% end %>
		<% end %>
		<% data << entry %>
	<% end %>
	<!-- Make Graph -->
	<%= image_tag Gchart.bar(:title => title, :bar_width_and_spacing => '13,4', :size => '640x300', :data => data, :labels => labels, :legend => legend, :stacked => false, :bar_colors => bar_colors, :vAxis => true) %>
	<br /><br /><br />
<% end %>

app/views/pages/_factoid_slide.html.erb
<%= image_tag factoid_slide.picture :class => "round" %>

app/views/pages/_overall_result_for_q.html.erb
<!-- COLLECT THE DATA -->
<% q = overall_result_for_q %>
<% title = "Question #{q.id}" %>
<% labels = [] %>
<% data = [] %>

<!-- Make the display -->
<p><b><%= title %></b> - <%= q.prompt %></p>	
<% q.options.split(' | ').each_with_index do |option, index| %>
	<dd <%="style='font-weight: bold'" if q.answer == index+1 %>><%= index+1 %>) <%= option %></dd>
	<% data << User.where("q#{q.id}" => option).count %>
	<% labels << "#{index}" %>
<% end %>	
<%= image_tag Gchart.pie_3d(:title => title, :size => '640x240', :data => data, :labels => labels )%>
<br /><br /><br />

app/views/pages/_random_demograph_for_q.html.erb
<!-- Demographic Specific Fixed Data -->
<% q = random_demograph_for_q %>
<% filter_question = Question.find(1+rand(5)) %>
<% filter_field = "q#{filter_question.id}" %>
<% legend = filter_question.options_array %>
<% color_options = ["FF0000","00FF00","0000FF","00FFFF","FF00FF","FFFF00"]%>
<% bar_colors = color_options[0..legend.count].join(",") %>

<!-- Param initialization -->
<% data = [] %>
<% labels = [] %>

<!-- Text Display and Options Parameter Fill -->
<% title = "Question #{q.id}" %>
<p><b><%= title %></b> - <%= q.prompt %></p>
<% q.options_array.each_with_index do |opt, i| %>
	<dd <%="style='font-weight: bold'" if q.answer == i+1 %>><%= i+1 %>) <%= opt %></dd>
	<% labels << "#{i+1}" %>
<% end %>

<!-- Setup Graph Data -->
<% legend.each do |filter_value| %>	
	<% entry = [] %>
	<% q.options.split(' | ').each do |option| %>
		<% if filter_value == "All" %>
			<% entry << User.where("q#{q.id} = ?", option).count %>
			<% User.where("q#{q.id} = ?", option).count %>
		<% else %>
			<% entry << User.where("#{filter_field} = ? AND q#{q.id} = ?", filter_value, option).count %>
			<% User.where("#{filter_field} = ? AND q#{q.id} = ?", filter_value, option).count %>
		<% end %>
	<% end %>
	<% data << entry %>
<% end %>
<!-- Make Graph -->
<%= image_tag Gchart.bar(:title => title, :bar_width_and_spacing => '13,4', :size => '640x300', :data => data, :labels => labels, :legend => legend, :stacked => false, :bar_colors => bar_colors, :vAxis => true) %>
<br /><br /><br />

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Small snippet about the research project in general.</p>
<h2>Researchers</h2>
<p>Snippet about researchers in general</p>
<div id="Bio">
<h3>Name</h3>
	<%= gravatar_image_tag 'example@railstutorial.org' %>
	<p>Small professional bio</p>
</div>
<h2>Additional Info</h2>
<table>
	<tr>
		<th>Resource</th>
		<th>URL</th>
	</tr>
	<tr>
		<td><%= link_to "One and only one Campaign", "http://www.oneandonlycampaign.org/" %></td>
		<td>http://www.oneandonlycampaign.org/</td>
	</tr>
</table>

app/views/pages/home.html.erb
<h1>Single Use Safety</h1>
<!-- GET ERROR DISPLAY -->
<% if flash[:notice].nil? == false %>
	<div id="notice" class="success">
	  <%= flash[:notice] %>
	</div>
<% end %>
<p>Welcome ASA Members!  You are invited to take our survey about safe injection practices.  Survey results are collected anonymously.  Email addresses will be used to send information about survey results and best practices if you so choose.</p>
<%= link_to "Take the survey!", survey_path, :class => "signup_button round"%>

app/views/pages/random.html.erb
<% content_for :head do %>
	<!-- Refresh every 5 seconds -->
	<meta http-equiv="refresh" content="60" /> 
<% end %>

<% option = rand(3) %>
<% random_index = 0 %>
<% while(Question.exists?(random_index) == false) %>
	<% random_index = 1 + rand(Question.all.count) %>
<% end %>
<% if option == 0 %>
	<%= render :partial => 'overall_result_for_q', :object => Question.find(random_index) %>
<% elsif option == 1 %>
	<%= render :partial => 'random_demograph_for_q', :object => Question.find(random_index)%>
<% elsif option == 2 %>
	<% index = 0 %>
	<% while(Factoid.exists?(index) == false) %>
		<% index = 1 + rand(Factoid.all.count) %>
	<% end %>
	<%= image_tag Factoid.random.picture, :class => "round" %>
<% end %>

app/views/pages/results.html.erb
<h1>Survey Results</h1>
<p>Overall results are provided as well as results by demographic information.  Answers in bold mark best practice where appropriate.  Results are updated semi-live, so feel free to check back.</p>
<%= link_to "Overall Results", overall_results_path %><br />
<%= link_to "Results by Gender", results_by_gender_path %><br />
<%= link_to "Results by Practice Setting", results_by_setting_path %><br />
<%= link_to "Results by Age", results_by_age_path %><br />
<%= link_to "Results by Experience", results_by_experience_path %><br />
<%= link_to "Results by Region", results_by_region_path %><br />

app/views/pages/results_by_age.html.erb
<h1>Results by Age</h1>
<%= render :partial => "demograph", :object => 2 %>
<%= link_to 'Back to Results', results_path %>

app/views/pages/results_by_experience.html.erb
<h1>Results by Experience</h1>
<%= render :partial => "demograph", :object => 4 %>

app/views/pages/results_by_gender.html.erb
<h1>Results by Gender</h1>
<%= render :partial => "demograph", :object => 3 %>

app/views/pages/results_by_region.html.erb
<h1>Results by Region</h1>
<%= render :partial => "demograph", :object => 5 %>

app/views/pages/results_by_setting.html.erb
<h1>Results by Practice Setting</h1>
<%= render :partial => "demograph", :object => 1 %>

app/views/pages/thanks.html.erb
<h1>Thank you for taking our survey!</h1>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :priority %><br />
    <%= f.text_area :priority, :rows => "5"%>
  </div>
  <div class="field">
    <%= f.label :prompt %><br />
    <%= f.text_area :prompt %>
  </div>
  <div class="field">
    <%= f.label :options %><br />
    <%= f.text_area :options %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>
	<div class="field">
		<%= f.label :responsetype %><br>
		<%= f.text_field :responsetype %>
	</div>
  <div class="field">
    <%= f.label :response %><br />
    <%= f.text_area :response %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
		<th>#</th>
		<th>ID</th>
    <th>Prompt</th>
    <th>Options</th>
    <th>Answer</th>
    <th>Response</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
		<td><%= question.priority %></td>
		<td><%= question.id %></td>
    <td><%= question.prompt %></td>
    <td><%= question.options %></td>
    <td><%= question.answer %></td>
    <td><%= question.response %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= button_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Prompt:</b>
  <%= @question.prompt %>
</p>

<p>
  <b>Options:</b>
  <%= @question.options %>
</p>

<p>
  <b>Answer:</b>
  <%= @question.answer %>
</p>

<p>
  <b>Response:</b>
  <%= @question.response %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>

app/views/users/_form.html.erb
<script language="JavaScript">
function SelectAnswer(questionID, selected_ans, correct_ans) {	
	//Get elements
	var inputElements = document.getElementsByTagName("input")
	var input
	var rightAnswer = false

	//Check against regext and disable if it matches given ID
	for(var i = 0; i < inputElements.length; i++) {
		input = inputElements[i]
		if(input.id.match('.*_' + questionID + '_.*')) {
			input.disabled = true;
		}
	}
		
	//Setup element var, this could fail if there is no element at which point
	//nothing else will be executed so be careful about that
	var responseElement = document.getElementById(questionID+"_response")
	
	//Show the prompt
	if(responseElement != null) {
		if(selected_ans == correct_ans) {
			responseElement.className='success';			
		}
		else{
			responseElement.className='error';
		}
		responseElement.style.display='block';			
	}
}
</script>
<script language ="JavaScript">
function EnableButtons() {
	//Get elements
	var inputElements = document.getElementsByTagName("input")
	var input
	
	//Re-enabled the buttons so they work for submitting data
	for(var i = 0; i < inputElements.length; i++) {
		input = inputElements[i] 
		if(input.disabled == true) {
			input.disabled = false;
		}
	}	
}
</script>
<%= form_for(@user) do |f| %>
<%= hidden_field params, :locks %>
	<p>Do not select an answer until you are certain of your selection as options will lock.  </p>
	</section>
	<!-- GET ERROR DISPLAY -->
	<% if @user.errors.any? %>
	<section class="round">
		<div id="error_explanation" class="error">
		<h3><%= pluralize(@user.errors.count, "error") %> prohibited the results from being saved:</h3>
		<ol>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ol>
		</div>
	<% end %>
	
	<!-- GET QUESTIONS DISPLAY -->
	<% Question.find(:all, order: :priority).each_with_index do |q,i| %>
		</section>
		<section class="round">
		<span class="prompt"><%= q.priority %>) <%= q.prompt %></span>	<br />
		<span class="options">
			<% if q.options.nil? == false && q.options.empty? == false %>
				<% q.options.split(' | ').each_with_index do |a,i| %>
					<% disable_value = true %>
					<% disable_value = false if @user["q#{q.id}"].nil? || params[:action] == "edit" %>
					 <%= f.radio_button "q#{q.id}", a, {onclick: "SelectAnswer('q#{q.id}','#{i}','#{q.answer}')", disabled: disable_value } %> <%= a %><br />
				<% end %>
			<% end %>
		</span>

		<% if q.response.nil? == false && q.response.empty? == false %>
			<br />
			<div class="" id="q<%=q.id%>_response" style="DISPLAY: none">
				<%= q.response %>
			</div>
		<% end %>	
	<% end%>

	<!-- GET EMAIL -->
	</section>
	<section class="round">
	<div class="field">
		<h3>Optional</h3>
		<p>Enter email to see results.  Your contact information will be saved separately from results. </p>
		<%= f.label :email %>  <%= f.text_field :email %>
	</div>
	
	<!-- SET SUBMIT -->
	</section>
	<section class="round">
	<div class="actions">
    	<%= f.submit 'Submit Results', :class => "submit_button round", :onclick=>"EnableButtons()" %>
  	</div>
  
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<% User.all.each do |user| %>
	<h3>User <%= user.id %></h3>
	<div><dd><b>ID:</b> <%= user.id %></dd></div>
	<div><dd><b>Created @:</b> <%= user.created_at.to_s %></dd></div>
	<div><dd><b>Updated @:</b> <%= user.updated_at.to_s %></dd></div>
	<ul>
		<li><%= link_to 'Show', user %></li>
		<li><%= link_to 'Edit', edit_user_path(user) %> </li>
		<li><%= button_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></li>
	</ul>
	<br /><br />
<% end %>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h3>User <%= @user.id %></h3>
<% @user.attributes.sort.each do |key, value|%>
	<% if value.nil? == false %>
	 <div><dd><b><%= "#{key}" %></b><%= " = #{value}" %></dd></div>
	<% end %>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>